### ISSUE TITLE
members-membership

### ISSUE THREAD

**Issue by lucasvp** [ccppbrasil/ccppbrasil#13]
Bom dia,

Sou diretor de tecnologia da Aker Security Solutions e desenvolvemos as aplicações em C/C++, gostaria de participar deste grupo para contribuir e aprender.

Valeu
Lucas

**Comment by caloni** [comment]
Seja bem-vindo!

[]s

**Comment by oblitum** [comment]
@lucasvp Convite para organização no github foi enviado.
