### ISSUE TITLE
Member Issue

### ISSUE THREAD

**Issue by alexandreiftm** [ccppbrasil/ccppbrasil#14]

**Comment by skhaz** [comment]
Feito.

**Comment by caloni** [comment]
?

**Comment by oblitum** [comment]
@caloni: http://www.ccppbrasil.org/faq/como-participar-do-grupo/

**Comment by oblitum** [comment]
@caloni a propósito o senhor ainda não é membro público (não conta na galeria da organização pra quem está navegando de fora dela).

**Comment by madera** [comment]
Broken Link: https://github.com/orgs/ccppbrasil/members

2015-03-25 22:06 GMT-03:00 Francisco Lopes notifications@github.com:

**Comment by oblitum** [comment]
@madera fixed via editor github dois palito ;-)

vlw

**Comment by caloni** [comment]
E como é que faz para se tornar público?

[]s

2015-03-25 22:06 GMT-03:00 Francisco Lopes notifications@github.com:

> @caloni https://github.com/caloni a propósito o senhor ainda não é
> membro público (não conta na galeria da organização pra quem está navegando
> de fora dela).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccppbrasil/ccppbrasil/issues/14#issuecomment-86273056
> .

## 

Wanderley Caloni
http://www.caloni.com.br

**Comment by oblitum** [comment]
@caloni se me recordo é só dar um check na página dos membros.

**Comment by oblitum** [comment]
@caloni a sim, fora aparecer na grade publicamente, seu profile no github vai ficar com a badge da organização, abaixo do seu avatar.

**Comment by caloni** [comment]
Done =)

2015-03-25 22:57 GMT-03:00 Francisco Lopes notifications@github.com:

> @caloni https://github.com/caloni se me recordo é só dar um check na
> página dos membros.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccppbrasil/ccppbrasil/issues/14#issuecomment-86292046
> .

## 

Wanderley Caloni
http://www.caloni.com.br

**Comment by oblitum** [comment]
> Done =)

fyi, não estou vendo efeito (private na lista e sem badge no seu profile).
