### ISSUE TITLE
Criar sala no gitter e adicionar ponte para o canal IRC

### ISSUE THREAD

**Issue by vinipsmaker** [ccppbrasil/ccppbrasil#22]
Recentemente [habilitei suporte ao gitter.im para o meu projeto, Tufão,](https://gitter.im/vinipsmaker/tufao) e depois [habilitei uma ponte para sincronizar as mensagens entre a sala no gitter e o canal no IRC](https://github.com/finnp/gitter-irc-bot). Essa solução é ótima, pois não exclui usuários que prefiram qualquer uma das escolhas.

A [sala IRC do canal](https://kiwiirc.com/client/chat.freenode.net/#ccppbrasil), assim como toda a rede do IRC, está morrendo. O pior da rede IRC é que ela é muito exclusiva, pois caso os usuários sejam de TZs diferentes, e não tenham como conseguir um IRC bouncer, simplesmente não dá para manter a comunicação. Fora que o IRC em si é muito complicado para quem só quer entrar em uma sala de bate papo.

O gitter também possui outras vantagens, como o fato de manter um log fácil de acessar para usuários que chegam depois. Enfim, fiquei contente com a integração, e resolvi vim aqui dar pitaco e sugerir a galera do grupo a também testar essa solução. Opiniões?

**Comment by oblitum** [comment]
Acho bem legal a idéia, só não tenho a impressão que toda a rede IRC esteja morrendo. Quantas redes já morreram e o IRC permaneceu, e pra mim pessoalmente ainda é um dos lugares onde encontro um pessoal mais hacker em um assunto específico disponível a dar respostas instantâneas. Concordo que BR são poucos que usam, e no geral consideram como algo de um passado remoto, mas IMO isto é um problema cultural regional, infelizmente.

**Comment by oblitum** [comment]
Não só isto mas uma infinidade de coisas relacionadas a software.

**Comment by vinipsmaker** [comment]
Beleza, levantei os serviços para a galera testar: https://gitter.im/ccppbrasil/ccppbrasil

Depois do teste a gente toma uma decisão. Porém, não vejo nenhuma razão para revertar a mudança, pois não compromete/atrapalha nenhum serviço. É bem suave. Não é intrusiva. etc (não estou conseguindo achar a palavra que quero)

**Comment by vinipsmaker** [comment]
Razões para rejeitar essa mudança:
- Possível SPAM (mas isso a gente só faz se começar a aparecer).
- Agora existe um bot fazendo log das conversas. Alguns usuários do IRC não gostam disso. Na verdade, parece que há algumas regras no Freenode para, caso você esteja fazendo log das mensagens, os usuários precisam ser informados (normalmente uma nota no tópico do canal IRC é o suficiente, mas a gente precisa saber quem tem poder de mudar a mensagem do tópico).

**Comment by oblitum** [comment]
@pedrolamarao é o criador do channel.

Por mim tá ok, apesar do log do IRC forçado não me agradar muito, mas sem problemas.

**Comment by vinipsmaker** [comment]
Eita, recebi um email do Heroku, relacionado ao bot que configurei para o canal do `#tufao` e do `#ccppbrasil`:

> Your app gittertufaobot2 is running on free dynos and has been active for more than 18 of the last 24 hours. Normally, your app would sleep for the next 6 hours. Don't worry, your app is still running - during the public beta we're simply sending notifications to raise awareness so you have ample time to adjust.
> 
> Why are you receiving this and what can you do?
> - Your app is becoming more popular. Upgrade your app to Hobby dynos for $7 per dyno per month so it never sleeps and users can access it 24×7.
> - A monitoring service could unintentionally be keeping your app awake for more than 18 hours a day. Run heroku logs -t to view your app's logs to see if this is the case and remove Pingdom, New Relic or other availability monitoring services that are not required for a free development app.
> - Your application may be receiving traffic from some other automated source. In order to sync up your app's sleep cycle with your own, scale it down before going to bed. In the morning, turn your app back on.
> - Your application may not have a web process at all. Once worker-only apps are started, they run for 18 hours and then sleep for 6 hours. After this your dynos will be started again. You can avoid this by upgrading to a hobby dyno, or by manually scaling down your application for six hours at a time that is convenient for you.
> 
> Dyno sleeping lets us provide you and millions of other users with a free tier for experimenting, hacking on personal projects and even low traffic apps that don't require 24×7 access.

Eu tenho uma VPS, e como o bot é open source, posso migrar ele para essa VPS. Seria legal hospedar naquele servidor que rodava a wiki do ccppbrasil?

**Comment by vinipsmaker** [comment]
Migrei o bot para a nuvem da RedHat, o OpenShift, que é sem pegadinha. Tudo resolvido agora.

**Comment by vinipsmaker** [comment]
> a nuvem da RedHat, o OpenShift, que é sem pegadinha

[A nuvem da RedHat colocou o aplicativo em idle e o bot perdeu uma mensagem](https://developers.openshift.com/en/managing-idling.html), mas [dá para deixar o aplicativo rodando 24h mesmo na conta gratuita](http://stackoverflow.com/questions/25379410/ping-service-to-stop-openshift-application-from-idle).

Enfim, estou monitorando a integração e, como não vi oposição, só faltaria o @pedrolamarao colocar link para os logs no tópico do canal IRC e eu posso fechar essa issue.

**Comment by pedrolamarao** [comment]
Eu ainda tenho autoridade sobre aquele canal? Alguém pode checar qual é o
nick do owner, e qual é o email associado a esse nick? Não estou em
condições de fazer isso hoje. P.

Em Ter, 30 de jun de 2015 21:09, Vinícius dos Santos Oliveira <
notifications@github.com> escreveu:

**Comment by vinipsmaker** [comment]
> Alguém pode checar qual é o nick do owner, e qual é o email associado a esse nick?

```

**Comment by vinipsmaker** [comment]
> Alguém pode checar qual é o nick do owner, e qual é o email associado a esse nick?

```
/msg ChanServ INFO #ccppbrasil
```

```
-ChanServ- Information on #ccppbrasil:
-ChanServ- Founder    : freenode-staff
-ChanServ- Registered : Apr 12 19:45:26 2008 (7y 11w 3d ago)
-ChanServ- Last used  : Apr 23 01:53:59 2009 (6y 9w 6d ago)
-ChanServ- Mode lock  : +ntc-s
-ChanServ- URL        : http://www.ccppbrasil.org/
-ChanServ- Flags      : KEEPTOPIC TOPICLOCK
-ChanServ- *** End of Info ***
```

**Comment by vinipsmaker** [comment]
> Alguém pode checar qual é o nick do owner, e qual é o email associado a esse nick?

```
Topico #ccppbrasil por PedroLamarao (Tue Nov 11 09:54:13 2008)
```

```
/msg NickServ INFO PedroLamarao
```

```
-NickServ- PedroLamarao is not registered.
```

**Comment by pedrolamarao** [comment]
Meu antigo nick expirou e o canal foi apropriado pelo governo. Tem que
ligar lá e pedir reintegração de posse. P.

Em ter, 30 de jun de 2015 às 21:23, Vinícius dos Santos Oliveira <
notifications@github.com> escreveu:

**Comment by vinipsmaker** [comment]
Fui atrás do "governo". =P
- [Nosso canal segue as regras de ON-TOPIC do freenode, pois entra na categoria "Geographically-Based Interest Group"](http://freenode.net/policy.shtml#ontopic). No caso, somos "Brazil's C++ User Group".
- [Nicks sempre expiram após 15 semanas de desuso](http://freenode.net/faq.shtml#userexpirations).
- [Canais que começam com um único `#` (ex.: `#ccppbrasil`) não expiram automaticamente](http://freenode.net/faq.shtml#channelexpirations).
- Não achei informações relacionadas a recuperação de canais no FAQ do Freenode. Tentarei entrar em contato com o _staff_.

**Comment by vinipsmaker** [comment]
Consegui uma resposta no canal `#freenode`, mas não acho que tenha sido de um staff member:

> &lt;Fuchs&gt; vinipsmaker: that doesn't sound too off. See if you can get hold of staff in here, if you can't: email projects at freenode dot net    with a description of that group, your role in it, the channel and your nickname here

**Comment by vinipsmaker** [comment]
Mensagem que mandei para projects at freenode dot net:

> Hi,
> 
> I'm part of the "C & C++ Brasil", a Brazilian's C++ User Group and we use a
> channel on the Freenode network, the channel #ccppbrasil. Unfortunately,
> the channel founder, PedroLamarao, lost his nick and control went to
> freenode-staff. Fortunately, the founder has set the channel URL before he
> lost his nick, the url http://www.ccppbrasil.org/. Thanks to this move,
> we can prove we represent the channel #ccppbrasil.
> 
> So, I'd like to request ownership of the #ccppbrasil channel. My nick on
> freenode is vinipsmaker.

**Comment by vinipsmaker** [comment]
> [...] não vejo nenhuma razão para revertar a mudança, pois não compromete/atrapalha nenhum serviço. É bem suave. Não é intrusiva. etc (não estou conseguindo achar a palavra que quero)

Acho que a palavra que eu estava procurando nesse momento era _disruptiva_.

(auto-citação, o cúmulo do _forever alone_ =P)

**Comment by madera** [comment]
Essa sala do gitter ficou muito legal... achei muito bacana a iniciativa e
a implementação.

Congratulações!

2015-07-04 16:17 GMT-03:00 Vinícius dos Santos Oliveira <
notifications@github.com>:

**Comment by thradams** [comment]
Tb deixo os parabéns pela iniciativa do gitter, e tb por toda a parte do github que foi feita ate aqui.

-----Original Message-----

**Comment by vinipsmaker** [comment]
> Meu antigo nick expirou e o canal foi apropriado pelo governo. Tem que ligar lá e pedir reintegração de posse. P.

```
/msg ChanServ INFO #ccppbrasil
```

```
-ChanServ- Information on #ccppbrasil:
-ChanServ- Founder    : vinipsmaker
-ChanServ- Successor  : freenode-staff
-ChanServ- Registered : Apr 12 19:45:26 2008 (7y 15w 0d ago)
-ChanServ- Last used  : Apr 23 01:53:59 2009 (6y 13w 4d ago)
-ChanServ- Mode lock  : +ntc-s
-ChanServ- URL        : http://www.ccppbrasil.org/
-ChanServ- Flags      : KEEPTOPIC TOPICLOCK
-ChanServ- *** End of Info ***
```

Mudei o tópico, coloquei o pepper_chico como sucessor e [alterei o site do grupo para incluir a referência ao gitter](https://github.com/ccppbrasil/ccppbrasil.github.io/commit/5b96bfcaddafaeb4cfcb19b1b0c8bea3e753edd8).
