### ISSUE TITLE
members-membership

### ISSUE THREAD

**Issue by AndersonFirmino** [ccppbrasil/ccppbrasil#33]
Oi, sou desenvolvedor. 

E gostaria de ser membro do grupo. :smile:

**Comment by oblitum** [comment]
Convite enviado.

**Comment by AndersonFirmino** [comment]
Obrigado man :D :D :D

**Comment by oblitum** [comment]
np, bem vindo. Se quiser tornar sua visibilidade de participação do grupo pública: https://github.com/orgs/ccppbrasil/people?page=1.

Poucos seguem mas... "é bom".
