### ISSUE TITLE
membership

### ISSUE THREAD

**Issue by eliashenriqueferreira** [ccppbrasil/ccppbrasil#4]
Ok, acho que posso ajudar em alguma coisa pois estou com tempo. Sinceramente não sou um expert em edição. Mas estou disposto a encarar o desafio.

**Comment by oblitum** [comment]
@eliashenriqueferreira caso vá alterar/adicionar algo que seja de tamanho relevante, não uma mera correção, sugiro abrir uma issue sobre a alteração/adição, ou criar uma pull-request (o que seria melhor ainda), [no repositório do site](https://github.com/ccppbrasil/ccppbrasil.github.io) antes, para que haja uma revisão do seu conteúdo inicial.
