### ISSUE TITLE
membership

### ISSUE THREAD

**Issue by bcsanches** [ccppbrasil/ccppbrasil#5]
Por favor me adicionem ao site.

**Comment by oblitum** [comment]
@bcsanches Se torne um membro público ;-)

**Comment by skhaz** [comment]
Isso, nao fique com vergonha de fazer parte :)

**Comment by madera** [comment]
Ainda mais que o logotipo ficou bonitim abaixo da minha foto, no GitHub.

2014-02-06 Rodrigo Delduca notifications@github.com:

**Comment by bcsanches** [comment]
Como se vira membro público? Nem sabia que tinha isso...

# Bruno Sanches

http://www.pontov.com.br

**Comment by oblitum** [comment]
@bcsanches [vá até a lista de membros](https://github.com/orgs/ccppbrasil/members), encontre-se consigo mesmo e saia do armário.

**Comment by bcsanches** [comment]
Ahhhhhh :) Done! sai do armário :)

Obrigado

# Bruno Sanches

http://www.pontov.com.br

**Comment by oblitum** [comment]
@bcsanches Acabei de notar que não sei o tipo de membership que você requisitou, eu já havia te adicionado como "membros" antes, não sei se tinha notado. Pensei ser uma requisição pra ser editor do site também, e te adicionei.

**Comment by oblitum** [comment]
@bcsanches a propósito, atualizei a informação das flags de membership (aqui e no site).

**Comment by bcsanches** [comment]
Valeu Francisco, eu fui fuçando lá vi a página explicando pedido e dai fiz.

# Bruno Sanches

http://www.pontov.com.br

2014-02-06 Francisco Lopes notifications@github.com:

**Comment by joselucianorc** [comment]
**Boa Tarde**

Por gentileza me adicionem como membro do grupo.

**Comment by skhaz** [comment]
@joselucianorc feito.
