### ISSUE TITLE
members-membership

### ISSUE THREAD

**Issue by alexgarzao** [ccppbrasil/ccppbrasil#6]
Oi,

Eu gostaria de ser listado como membro do grupo também :-)

Abraços!

**Comment by oblitum** [comment]
@alexgarzao adicionado. Considere se tornar um membro público.

Att.

**Comment by msrmarcio** [comment]
Gostaria de ser listado no grupo também. Obrigado

**Comment by oblitum** [comment]
@msrmarcio convite foi enviado. Futuramente, caso precise entrar pra Editors, etc. crie uma issue propria, comentarios nao podem ser contabilizados de forma facil.
